// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Id    *int    `json:"id,omitempty"`
	Token *string `json:"token,omitempty"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	Message *string `json:"message,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostV1AuthLoginJSONBody defines parameters for PostV1AuthLogin.
type PostV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// PostV1AuthRegisterJSONBody defines parameters for PostV1AuthRegister.
type PostV1AuthRegisterJSONBody struct {
	ConfirmPassword string `json:"confirmPassword"`
	Email           string `json:"email"`
	Password        string `json:"password"`
}

// PostV1AuthLoginJSONRequestBody defines body for PostV1AuthLogin for application/json ContentType.
type PostV1AuthLoginJSONRequestBody PostV1AuthLoginJSONBody

// PostV1AuthRegisterJSONRequestBody defines body for PostV1AuthRegister for application/json ContentType.
type PostV1AuthRegisterJSONRequestBody PostV1AuthRegisterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login with email + password
	// (POST /v1/auth/login)
	PostV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// Login with email + password
	// (POST /v1/auth/register)
	PostV1AuthRegister(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Login with email + password
// (POST /v1/auth/login)
func (_ Unimplemented) PostV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login with email + password
// (POST /v1/auth/register)
func (_ Unimplemented) PostV1AuthRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostV1AuthRegister operation middleware
func (siw *ServerInterfaceWrapper) PostV1AuthRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostV1AuthRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/login", wrapper.PostV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/register", wrapper.PostV1AuthRegister)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWQU/bTBD9K6v5vlut2CkckG8gtRUVSAhKe0AcNt5JstTeXWbX0BT5v1ezdmKHJG1K",
	"4Rbveua9mfdmnCcobOWsQRM85E9A6J01HuPDiVSXeF+jDx+ILPFRYU1AE/indK7UhQzamvTOW8Nn+ENW",
	"rmyjp5YmWimMFw+yrLFNoBDywyxLoELv5QwhZyDRIeUCGUs4SV6bmVAySGiaJgFfzLGSnON/wink8F/a",
	"c0/bW5+2TGOAQl+QdkwQcrj2SEJ7IeswRxOYOSoxqYMwNsRTS/onKmgSOLMzbS67VuxR9n7UmME2ZoSh",
	"JiOC/Y5GSKNEHamaqaUq4jClS5xpH5BexMqRdUhBt8Ks+r7SC3K4qosCvRdLHEggLBzf+EDazIB5dyd2",
	"codF+E0p1CURvsu6hGwSuDZ9r19iq9qsKRgLratK0gJyONc+usZy/x5kqVXbVkg2HTgeOvB6PWsuql2Z",
	"XsOLxz2WtkZMpS5RMdQStSBU/IIsPfR4sf5Vz9ZFbasaKBoL7ATTJuCMzZdsF3//6re5gvC+1sRS3LQ0",
	"epTbDc8kcRA3+WMldck/nuVPQKvB8aCSltBmxBafJuCxqEmHxRU3skWcoCQklqJ/+hhHDnL4/O0LdG3n",
	"TO1tX/08BNcKy2MaSegQW3m++GTPpJkdOyeOL07ZeEi+lX08ykYZU7cOjXQacjgYZaMDSMDJMI+s0odx",
	"ymKkJe+g2Cfr42Bwt6JfThXkcGF9+Dpm9nFZQSsD+nBi1eIflsNuHZz0/tGS2t7yoQnaHIOI262row8J",
	"VGM8GHx83mfZrvlavZeuL+omgcNs/OeozRUULbLaIjGreNRhLmIp4p1YlcJvrjRa7rl9ZBos1tdRqrBm",
	"qqm62C1L8jZqJhvQb6bvxlcvSrxH4PO/Ln8jcFwXxGML+c0T1FR2E5+naWkLWc6tD/lRdpRBc9v8CgAA",
	"//9mL2+0QgkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
